# Site
title: PVIEITO
email: pvieito@gmail.com
author: Pedro José Pereira Vieito
creation_year: 2008
url: "https://pvieito.com"

# Localization
timezone: Europe/Madrid

# Resources
icon_url: "/resources/icon.png"
icon_mask_url: "/resources/icon.svg"

# Pages
paginate: 4
paginate_path: "/page/:num/"
permalink: "/:year/:month/:title"

# Feed
feed_limit: 25

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      lang: en
      layout: "post"

# Build
sass:
  style: compressed
exclude:
  - "Icon*"
include:
  - ".well-known"
plugins:
  - jekyll-paginate
