# Site
title: PVIEITO
email: pvieito@gmail.com
author: Pedro José Pereira Vieito
creation: 2008
url: "https://pvieito.com"

# Localization
timezone: Europe/Madrid

# Pages
paginate: 4
paginate_path: "/page/:num/"
permalink: "/:year/:month/:title"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      lang: es
      layout: "post"

# Build
sass:
  style: compressed
exclude:
  - "Icon*"
include:
  - ".well-known"
plugins:
  - jekyll-paginate
