name: Blog Deployment

on:
  push:
    branches:
      - master

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Jekyll
        run: |
            sudo gem install jekyll jekyll-paginate bundler
      - name: Deploy
        run: |
            git clone https://github.com/pvieito/JekyllTool $JEKYLLTOOL_SOURCE_DIR
            swift run --enable-test-discovery --package-path $JEKYLLTOOL_SOURCE_DIR JekyllTool -d -i .
        env:
            JEKYLLTOOL_SOURCE_DIR: /tmp/JekyllTool
